workflows:
  unity-ios:
    name: Build Unity iOS App
    environment:
      vars:
        UNITY_VERSION: 2022.3.31f1
      xcode: latest  # Указываем, что сборка будет проходить на macOS с последней версией Xcode
    scripts:
      - name: Install Unity
        script: |
          curl -o unity.pkg https://download.unity3d.com/download_unity/${UNITY_VERSION}/MacEditorInstaller/Unity.pkg
          sudo installer -pkg unity.pkg -target /
      - name: Build iOS App
        script: |
          UNITY_PATH="/Applications/Unity/Hub/Editor/${UNITY_VERSION}/Unity.app/Contents/MacOS/Unity"
          $UNITY_PATH -batchmode -quit -projectPath . -executeMethod BuildScript.BuildIOS \
            -buildTarget ios -customBuildPath build/ios
      - name: Export Xcode Project
        script: |
          mkdir -p build/ios
          cd build/ios
          xcodebuild -project <ProjectName>.xcodeproj \
            -scheme <SchemeName> -configuration Release \
            -archivePath App.xcarchive archive
    artifacts:
      - build/ios/App.xcarchive
      - build/ios/App.ipa

    publishing:
      scripts:
        - name: Export .ipa
          script: |
            xcodebuild -exportArchive \
              -archivePath build/ios/App.xcarchive \
              -exportOptionsPlist ExportOptions.plist \
              -exportPath build/ios/App.ipa
